import { About, Mentor } from "@/components/ui";
import Head from "next/head";

const AboutPage = () => {
  return (
    <>
      <Head>
        <title>COntact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-5">
        <About />
        <Mentor />
      </div>
    </>
  );
};

export default AboutPage;
