import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
import { About, HeroDiv } from "@/components/ui";
import { Cards } from "@/components/ui";

const technologies = [
  {
    name: "Python",
    image: "/images/technologies/python.png",
    description:
      "Python is an interpreted, high-level and general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.",
  },
  {
    name: "OpenCV",
    image: "/images/technologies/Open CV.png",
    description:
      "OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library. OpenCV was built to provide a common infrastructure for computer vision applications and to accelerate the use of machine perception in the commercial products. Being a BSD-licensed product, OpenCV makes it easy for businesses to utilize and modify the code.",
  },
  {
    name: "Python",
    image: "/images/technologies/YOLO.png",
    description:
      "YOLO (You Only Look Once) is a method / way to do object detection. It is the algorithm /strategy behind how the code is going to detect objects in the image. The official implementation of this idea is available through DarkNet (neural net implementation from the ground up in C from the author). It is available on github for people to use.",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>KMPS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroDiv />
      <Cards technologies={technologies} />
      <About />
    </>
  );
}
